package(default_visibility = ["//visibility:public"])

cc_library(
    name = "analysis",
    srcs = [
        "result_analysis.cc",
    ],
    hdrs = [
        "result_analysis.h",
        "result_structure.h",
    ],
    deps = [
        "//kv_cache_manager/common:logger",
        "//kv_cache_manager/optimizer/config",
    ],
)
