package(default_visibility = ["//visibility:public"])

cc_library(
    name = "analysis",
    hdrs = [
        "stats_collector.h",
        "stats_record.h",
        "stats_tracker.h",
    ],
    deps = [
        "//kv_cache_manager/common:logger",
        "//kv_cache_manager/optimizer/config",
    ],
)
