"""Generate version info files from Bazel stamp status files.

Usage (invoked by Bazel genrule with stamp = 1):
    python3 gen_version_info.py --format=python \
        --stable=bazel-out/stable-status.txt \
        --volatile=bazel-out/volatile-status.txt \
        --output=_version_info.py

    python3 gen_version_info.py --format=cpp \
        --stable=bazel-out/stable-status.txt \
        --volatile=bazel-out/volatile-status.txt \
        --output=build_version.h \
        --source-output=build_version.cc
"""

import argparse


def parse_status_file(path):
    """Parse a Bazel status file into a dict of key-value pairs."""
    result = {}
    try:
        with open(path, "r") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                parts = line.split(" ", 1)
                if len(parts) == 2:
                    result[parts[0]] = parts[1]
                elif len(parts) == 1:
                    result[parts[0]] = ""
    except FileNotFoundError:
        pass
    return result


def _escape_cpp_string(s):
    """Escape backslashes and double quotes for C++ string literals."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def generate_python(status_vars, output):
    version = status_vars.get("STABLE_KVCM_VERSION", "0.0.0")
    git_commit = status_vars.get("STABLE_GIT_COMMIT", "unknown")
    git_commit_full = status_vars.get("STABLE_GIT_COMMIT_FULL", "unknown")
    git_repo = status_vars.get("STABLE_GIT_REPO", "unknown")
    build_date = status_vars.get("BUILD_DATE", "unknown")
    build_timestamp = status_vars.get(
        "STABLE_BUILD_TIMESTAMP", status_vars.get("BUILD_TIMESTAMP", build_date)
    )
    build_time = status_vars.get("BUILD_TIME", "unknown")
    full_version = "%s+%s.%s" % (version, build_timestamp, git_commit)

    with open(output, "w") as f:
        f.write("# Auto-generated by Bazel build. Do not edit.\n")
        f.write("VERSION = %s\n" % repr(version))
        f.write("GIT_COMMIT = %s\n" % repr(git_commit))
        f.write("GIT_COMMIT_FULL = %s\n" % repr(git_commit_full))
        f.write("GIT_REPO = %s\n" % repr(git_repo))
        f.write("BUILD_DATE = %s\n" % repr(build_date))
        f.write("BUILD_TIMESTAMP = %s\n" % repr(build_timestamp))
        f.write("BUILD_TIME = %s\n" % repr(build_time))
        f.write("FULL_VERSION = %s\n" % repr(full_version))


def generate_cpp(status_vars, header_output, source_output):
    version = status_vars.get("STABLE_KVCM_VERSION", "0.0.0")
    git_commit = status_vars.get("STABLE_GIT_COMMIT", "unknown")
    git_commit_full = status_vars.get("STABLE_GIT_COMMIT_FULL", "unknown")
    git_repo = status_vars.get("STABLE_GIT_REPO", "unknown")
    build_date = status_vars.get("BUILD_DATE", "unknown")
    build_timestamp = status_vars.get(
        "STABLE_BUILD_TIMESTAMP", status_vars.get("BUILD_TIMESTAMP", build_date)
    )
    build_time = status_vars.get("BUILD_TIME", "unknown")
    full_version = "%s+%s.%s" % (version, build_timestamp, git_commit)

    constants = [
        ("kKvcmVersion", version),
        ("kKvcmGitCommit", git_commit),
        ("kKvcmGitCommitFull", git_commit_full),
        ("kKvcmGitRepo", git_repo),
        ("kKvcmBuildDate", build_date),
        ("kKvcmBuildTimestamp", build_timestamp),
        ("kKvcmBuildTime", build_time),
        ("kKvcmFullVersion", full_version),
    ]

    with open(header_output, "w") as f:
        f.write("#pragma once\n")
        f.write("// Auto-generated by Bazel build. Do not edit.\n")
        f.write("\nnamespace kv_cache_manager {\n\n")
        for name, _ in constants:
            f.write("extern const char %s[];\n" % name)
        f.write("\n} // namespace kv_cache_manager\n")

    with open(source_output, "w") as f:
        f.write("// Auto-generated by Bazel build. Do not edit.\n")
        f.write('\nnamespace kv_cache_manager {\n\n')
        # Namespace-scope const definitions need extern to match the header's external linkage.
        for name, value in constants:
            f.write('extern const char %s[] = "%s";\n' % (name, _escape_cpp_string(value)))
        f.write("\n} // namespace kv_cache_manager\n")


def main():
    parser = argparse.ArgumentParser(description="Generate version info from Bazel stamp files")
    parser.add_argument("--format", required=True, choices=["python", "cpp"])
    parser.add_argument("--stable", required=True, help="Path to stable-status.txt")
    parser.add_argument("--volatile", required=True, help="Path to volatile-status.txt")
    parser.add_argument("--output", required=True, help="Output file path")
    parser.add_argument("--source-output", help="Output source file path for --format=cpp")
    args = parser.parse_args()

    status_vars = {}
    status_vars.update(parse_status_file(args.stable))
    status_vars.update(parse_status_file(args.volatile))

    if args.format == "python":
        generate_python(status_vars, args.output)
    elif args.format == "cpp":
        if not args.source_output:
            parser.error("--source-output is required for --format=cpp")
        generate_cpp(status_vars, args.output, args.source_output)


if __name__ == "__main__":
    main()
