package(default_visibility = ["//visibility:public"])

filegroup(
    name = "start_server_script",
    srcs = [
        "start_server.sh",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "decode_stack_trace_script",
    srcs = [
        "decode_stack_trace.sh",
    ],
    visibility = ["//visibility:public"],
)
