package(default_visibility = ["//visibility:public"])

cc_library(
    name = "vipserver_service_discovery",
    srcs = [
        "vipserver_service_discovery.cc",
    ],
    hdrs = [
        "vipserver_service_discovery.h",
    ],
    deps = [
        "//kv_cache_manager/common:logger",
        "//kv_cache_manager/common:service_discovery",
    ],
)

cc_library(
    name = "spectrum_service_discovery",
    srcs = [
        "spectrum_service_discovery.cc",
    ],
    hdrs = [
        "spectrum_service_discovery.h",
    ],
    deps = [
        "//kv_cache_manager/common:logger",
        "//kv_cache_manager/common:service_discovery",
    ],
)
