package(default_visibility = ["//visibility:public"])

cc_library(
    name = "vipserver_subscriber",
    srcs = [
        "vipserver_subscriber.cc",
    ],
    hdrs = [
        "vipserver_subscriber.h",
    ],
    deps = [
        "//kv_cache_manager/common:logger",
    ],
)
