package(default_visibility = ["//visibility:public"])

cc_library(
    name = "spec_events",
    srcs = [],
    hdrs = [
        "cache_reclaim_event.h",
        "optimizer_event.h",
    ],
    deps = [
        "//kv_cache_manager/event:base_event",
        "//kv_cache_manager/manager:cache_location",
    ],
)

