cc_library(
    name = "tair_mempool_sdk",
    srcs = ["tair_mempool_sdk.cc"],
    hdrs = ["tair_mempool_sdk.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//kv_cache_manager/client/src/internal/sdk:sdk_common",
        "//kv_cache_manager/common",
    ],
)
