package(default_visibility = ["//visibility:public"])

filegroup(
    name = "default_optimizer_confs",
    srcs = [
        "default_optimizer_config.json",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "start_optimizer_server_script",
    srcs = [
        "start_optimizer_server.sh",
    ],
    visibility = ["//visibility:public"],
)
