ARG BASE_OS_IMAGE=alibaba-cloud-linux-3-registry.cn-hangzhou.cr.aliyuncs.com/alinux3/alinux3:latest
ARG BAZELISK_URL="https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-linux-amd64"
ARG BUILDIFER_URL="https://github.com/bazelbuild/buildtools/releases/download/v8.2.1/buildifier-linux-amd64"
ARG BAZELISK_BASE_URL=https://mirrors.huaweicloud.com/bazel/

FROM $BASE_OS_IMAGE
LABEL org.opencontainers.image.source=https://github.com/alibaba/tair-kvcache
LABEL org.opencontainers.image.description="Tair KVCache Manager Dev Container"
LABEL org.opencontainers.image.licenses=Apache-2.0

ARG BAZELISK_URL
ARG BUILDIFER_URL
ARG BAZELISK_BASE_URL

USER root

# libicu for CLion IDE
# pigz for bazel pkg_tar
# autopep8 buildifier clang-tools-extra(clang-format) for code format
# avoid using internal yum repo
RUN sed -i.bak 's|http://mirrors\.cloud\.aliyuncs\.com|http://mirrors.aliyun.com|g' /etc/yum.repos.d/*.repo && \
    yum install -y --setopt=timeout=3 libicu pigz libibverbs-devel librdmacm-devel numactl-devel  \
    cpio patchelf libaio-devel \
    vim gcc gcc-c++ libasan git openssh wget procps-ng iproute tar clang-tools-extra \
    python3.11 python3.11-pip python3.11-devel && \
    yum clean all && \
    rm -rf /var/cache/yum && \
    pip3 config set global.index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple && \
    pip3 install autopep8 && \
    wget "$BAZELISK_URL" -O /usr/local/bin/bazelisk && chmod a+x /usr/local/bin/bazelisk && \
    BAZELISK_BASE_URL=$BAZELISK_BASE_URL USE_BAZEL_VERSION=6.4.0 bazelisk && \
    wget "$BUILDIFER_URL" -O /usr/local/bin/buildifier && chmod a+x /usr/local/bin/buildifier


ENV KV_CACHE_MANAGER_DEV_VERSION __IMAGE_VERSION_PLACEHOLDER__