cc_test(
    name = "MooncakeBackendTest",
    srcs = [
        "mooncake_backend_test.cc",
    ],
    copts = ["-fno-access-control"],
    data = [],
    deps = [
        "//kv_cache_manager/data_storage",
        "//kv_cache_manager/common:unittest",
    ],
    tags = ["manual"]
)
