package(default_visibility = ["//visibility:public"])

cc_library(
    name = "util",
    srcs = [],
    hdrs = [
        "debug_string_util.h"
    ],
    deps = [
        "//kv_cache_manager/common",
    ],
)
